#!/usr/bin/env sh

TARGET=$(curl -sL https://gitignore.io/api/list | tr ',' '\n' | fzf --multi --cycle --border | tr '\n' ',' | sed 's/,$//')
echo "Downloading gitignore template for file type(s): ""$TARGET"
curl -sL -o .gitignore https://gitignore.io/api/"$TARGET"
