#!/usr/bin/env bash

OUT="$(mktemp)"
pandoc --from gfm --to html --standalone --quiet "$1" > "$OUT"

if [[ "$OSTYPE" == "darwin"* ]]; then
    open -a Firefox "$OUT"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    firefox "$OUT"
fi
