#!/usr/bin/env sh

# Iterate files in the PWD
for f in ./*
do
    # Extract the file's extension
    filename=$(basename "$f")
    ext="${filename##*.}"

    # Ensure that the file has an extension
    if [ "$filename" = "$ext" ]
    then
        ext="NONE"
    fi

    # Check to see if extension directory exists
    if [ ! -d "$ext" ]
    then
        # Create the directory if not previously present
        mkdir -- "$ext"
    fi

    # Move file to the folder named after its extension
    mv "$f" "$ext"
done
