#!/usr/bin/env bash

PIP_CMD='pip3'

PKGS=$($PIP_CMD list --outdated | tail +3 | cut -d ' ' -f 1)
NUM_PKGS=${#PKGS[@]}
echo "Packages doesn't word split correctly..."
exit

if [ "$NUM_PKGS" -eq 0 ]
then
    echo "Nothing to do..."
    exit 0
fi


printf "Installing %d packages...\n" "$NUM_PKGS"
exit

for pkg in $PKGS
do
    $PIP_CMD install --upgrade "$pkg" >/dev/null
    echo "Updated:    ""$pkg"
done

echo "All pip packages are up-to-date."
